version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 1972
      - 51773
      - 52773:52773
      - 53773
    volumes:
      - ./:/irisdev/app
      - ./src/csp:/opt/irisapp/src/csp
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    container_name: frontend
    stdin_open: true
    volumes:
       - ./frontend:/usr/src/app/frontend
       - /usr/src/app/frontend/node_modules
